# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-09 02:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_player_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='exp_avg',
        ),
    ]
